Method: ExceptionTryCatchFinally.Program..ctor[instance.void..()]

Trace 0
	[start] ExceptionTryCatchFinally.Program..ctor[instance.void..()]
	[ end ] ExceptionTryCatchFinally.Program..ctor[instance.void..()]

Method: ExceptionTryCatchFinally.Program.<Main>g__ThrowException|0_0[void..()]

Trace 0
	[start] ExceptionTryCatchFinally.Program.<Main>g__ThrowException|0_0[void..()]
	[ end ] ExceptionTryCatchFinally.Program.<Main>g__ThrowException|0_0[void..()]

Method: ExceptionTryCatchFinally.Program.Main[void..(class.System.String[])]

Trace 0
	[start] ExceptionTryCatchFinally.Program.Main[void..(class.System.String[])]
		[start] ExceptionTryCatchFinally.Program.<Main>g__ThrowException|0_0[void..()]
		[ end ] ExceptionTryCatchFinally.Program.<Main>g__ThrowException|0_0[void..()]
		[start] ExceptionTryCatchFinally.Program..ctor[instance.void..()]
		[ end ] ExceptionTryCatchFinally.Program..ctor[instance.void..()]
	[ end ] ExceptionTryCatchFinally.Program.Main[void..(class.System.String[])]

